<?php

namespace Administracion\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
     /*
     * Hacer un metodo que retorne todas los clientes donde coincida en al menos un campo de los que 
     * se muestran en el buscador con un texto que se pasara como parametro
     */

    public function findClienteByTexto($texto) {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
		  SELECT c FROM ModeloBundle:Cliente c 
		  JOIN c.telefonos t
		  JOIN c.domicilios d
		  WHERE c.nombre LIKE :texto 
		  OR c.apellido LIKE :texto
		  OR t.numero LIKE :texto
                  OR t.celular LIKE :texto
		  OR d.localidad LIKE :texto   
		  OR d.calle LIKE :texto                   
		  ORDER BY c.id DESC
		');
        $consulta->setParameter('texto', '%' . $texto . '%');
        return $consulta->getResult();
    }

    /*
     * Hacer un metodo que retorne todos los clientes cuyo apellido comience con una letra que se 
     * pasara como parametro
     */

    public function findClienteByApellido($letra, $sucursal) {        
        $em = $this->getEntityManager();
        
        $consulta = $sucursal ? $em->createQuery('
		  SELECT c FROM ModeloBundle:Cliente c 
		  WHERE c.apellido LIKE :letra 
                  AND c.sucursal = :sucursal
		  ORDER BY c.apellido DESC
		') 
                : $em->createQuery('
		  SELECT c FROM ModeloBundle:Cliente c 
		  WHERE c.apellido LIKE :letra                   
		  ORDER BY c.apellido DESC
		') ;
        $consulta->setParameter('letra', $letra . '%');
        if($sucursal)
            $consulta->setParameter('sucursal', $sucursal);
        return $consulta->getResult();
    }
    
    public function GenerarCodigoCliente()
    {
        $codigo = "CL/";
        $em = $this->getEntityManager();
        $consulta = $em->createQuery(' SELECT c.id FROM ModeloBundle:Cliente c	ORDER BY c.id DESC')->setMaxResults(1);        
        $id = $consulta->getResult(); 
        $codigo .= str_pad( (count($id) > 0 ? $id[0]['id'] : 0) + 1, 6, '0', STR_PAD_LEFT);
        
        return $codigo;
    }
    
  
}
