<?php

namespace Administracion\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComandaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComandaRepository extends EntityRepository
{
    public function findComandasHoy($sucursal = null)
    {
         $em = $this->getEntityManager();         

         $sql = 'SELECT c FROM ModeloBundle:Comanda c WHERE c.fecha >= :fecha'; 	  
         
         if($sucursal)
             $sql .= ' and c.sucursal = :sucursal';
         
         $consulta = $em->createQuery($sql);
	 $consulta->setParameter('fecha', new \DateTime('today'));	  
	
         if($sucursal)
             $consulta->setParameter('sucursal',$sucursal);
         
         return $consulta->getResult(); 
    }
    
    public function findComandas($sucursal = null)
    {
         $em = $this->getEntityManager();         

         $sql = 'SELECT c FROM ModeloBundle:Comanda c '; 	  
         
         if($sucursal)
             $sql .= ' WHERE c.sucursal = :sucursal';
         
         $consulta = $em->createQuery($sql);
	
         if($sucursal)
             $consulta->setParameter('sucursal',$sucursal);
         
         return $consulta->getResult(); 
    }    
        
     public function findComandasByEstadoSucursal($estado, $sucursal )
    {
         $em = $this->getEntityManager();
	 $consulta = $em->createQuery('
		  SELECT c 
		  FROM ModeloBundle:Comanda c 		  
		  WHERE c.estado = :estado 
		  AND c.sucursal = :sucursal
		  ORDER BY c.id DESC
		');
	 $consulta->setParameter('estado', $estado);
	 $consulta->setParameter('sucursal', $sucursal->getId());
	 return $consulta->getResult();
    }
        
    public function GenerarCodigoComanda($sucursal)
    {        
        $em = $this->getEntityManager();
        $comandas = $em->getRepository('ModeloBundle:Comanda')->findBy(array('sucursal'=>$sucursal));
        if(count($comandas) > 0){            
            $numero = count($comandas) + 1; 
        } else{
            $numero = 1;
        }
        $codigo = strtoupper(substr($sucursal->getNombre(), 0, 2))."/";
        $codigo .= str_pad($numero, 6, '0', STR_PAD_LEFT);
        
        return $codigo;
    }
    
    public function CambiarEstadoComandaDemorada()
    {
        $em = $this->getEntityManager();
        $comandas = $em->getRepository('ModeloBundle:Comanda')->findBy(array('estado'=>2)); 
        foreach($comandas as $comanda){
            $creacion = $comanda->getHora();
            $ahora = new \DateTime('now');
            $intervalo = $creacion->diff($ahora);
            
            $diferenciaDias = $intervalo->format('%d');
            $diferenciaHoras = $intervalo->format('%h');
            $diferenciaMinutos = $intervalo->format('%i');
            
            $minutos = array('1'=>40, 2=>50, 3=>90 );
            
            $diferenciaMinutos += $diferenciaHoras > 0 ? $diferenciaHoras * 60 : 0;
            
            if($diferenciaDias > 0 || $minutos[$comanda->getTiempoDemora()] < $diferenciaMinutos ){
                $comanda->setEstado(4);
                $em->persist($comanda);
            }
        }

        $em->flush();
    }
		
}
